# Generated by Django 3.2.12 on 2022-04-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HW7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.PositiveIntegerField(default=4108056005)),
                ('pub_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
