# Generated by Django 3.1.2 on 2022-03-29 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('R', 'Rice'), ('N', 'Noodles'), ('D', 'Dumpling'), ('d', 'dishes')], max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('is_spicy', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-pub_time',),
            },
        ),
    ]
