# Generated by Django 3.2.12 on 2022-05-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_byear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='匿名', max_length=50)),
                ('city', models.CharField(choices=[['TP', 'Taipei'], ['TC', 'TaiChung'], ['TN', 'Tainan'], ['O', 'Others']], max_length=50)),
                ('school', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='byear',
            field=models.IntegerField(default=2022),
        ),
    ]
