# Generated by Django 3.2.12 on 2022-04-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilemarket', '0002_alter_product_pmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pmodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobilemarket.pmodel', verbose_name='型號'),
        ),
    ]
