# Generated by Django 3.1.2 on 2022-05-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining_brief', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
